### ISSUE TITLE
Implementing PSR-2 maybe and adding .editorconfig maybe?

### ISSUE THREAD

**Issue by eXtreme** [zyxist/cantiga#19]
I know personal preferences may be crucial but following PSR-2 on opensource symfony-based project would be good for contributing.

The main issue I see here is using tabs and when you look through the code on github you'll notice it is inconsistent because leading spaces are here or there (tabs on github are expanded to 8 for default so you can easily spot the difference).

There is a great tool, Sensio CS Fixer, http://cs.sensiolabs.org/ which helps keeping the code in a good shape. You can run it with `--level=symfony` to ensure it follows the same CS as Symfony or use `prs2` setting to ensure it's psr2 compliant. 

Later, I suggest creating a `.editorconfig` file in the root of the project, it is recognized by major IDEs and code editors (either native or by plugin) and allows consistent encoding, tabs, and other preferences for source projects. More on this: http://editorconfig.org/

For this project I suggest the following: 

``` ini
root = true

[*]
end_of_line = LF
charset = utf-8

[*.php]
indent_style = space
indent_size = 4
insert_final_newline = true

[*.yml]
indent_style = space
indent_size = 4

[*.json]
indent_style = space
indent_size = 4

[*.twig]
indent_style = space
indent_size = 4

[*.md]
trim_trailing_whitespace = false
```

of course it can be tweaked for future other file formats.

**Comment by zyxist** [comment]
`.editorconfig` added. Unfortunately I cannot test it, because the plugin for NetBeans seems not to work (or I'm doing something very wrong).

I appreciate the work of folks from PHP Interop Group, but I work with both tab- and space-based projects on daily basis and see that spaces cause more problems than they solve. However, this is not a place for discussion for that. If this were Symfony, I'd use spaces. But it is not. Just go on and adapt, like me :).
